NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: ""
RUN_N_TIMES: 1
MODEL:
  TRANSFER_TYPE: "linear"
  TYPE: "vit"
  LINEAR:
    MLP_SIZES: []
SOLVER:
  LOSS: "softmax"
  OPTIMIZER: "sgd"
  SCHEDULER: "cosine"
  MOMENTUM: 0.9
  WARMUP_EPOCH: 10
  TOTAL_EPOCH: 100
  PATIENCE: 300
  LOG_EVERY_N: 1
  WEIGHT_DECAY: 0.0001
DATA:
  NAME: ""
  NUMBER_CLASSES: -1
  DATAPATH: ""
  FEATURE: "sup_vitb16_224"
  BATCH_SIZE: 1024